# Generated by Django 4.2.7 on 2023-11-16 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FE', '0003_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_field',
            new_name='profile_message',
        ),
    ]
