# Generated by Django 4.2.7 on 2023-11-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
