# Generated by Django 4.2.7 on 2023-11-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0009_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
