# Generated by Django 4.2.7 on 2023-11-28 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FE', '0010_profile_datetimeofupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dehazing',
            name='user',
            field=models.OneToOneField(default=13, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='after_fog/'),
        ),
    ]
