# Generated by Django 4.2.7 on 2023-11-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0013_postform_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parentcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.comment'),
        ),
    ]
