# Generated by Django 4.2.7 on 2023-12-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0014_alter_comment_options_comment_parentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
