# Generated by Django 4.2.7 on 2023-12-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0015_comment_is_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='FE.comment'),
        ),
    ]
